# Generated by Django 5.2.3 on 2025-06-27 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friend',
            old_name='deleted_time',
            new_name='deleted_at',
        ),
        migrations.RenameField(
            model_name='notificationsetting',
            old_name='deleted_time',
            new_name='deleted_at',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='deleted_time',
            new_name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='friendshiprequest',
            name='deleted_time',
        ),
        migrations.AddField(
            model_name='friendshiprequest',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
