# Generated by Django 5.2.3 on 2025-06-27 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='deleted_time',
            new_name='deleted_at',
        ),
    ]
