# Generated by Django 5.2.3 on 2025-06-26 14:06

import common.snowflake
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenChatRoom',
            fields=[
                ('id', models.BigIntegerField(default=common.snowflake.generate_id, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_time', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('notice', models.CharField(blank=True, max_length=255, null=True)),
                ('maximum_capacity', models.IntegerField(default=2)),
                ('current_attendance', models.IntegerField(default=1)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='categories.category')),
                ('manager', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='users.user')),
            ],
            options={
                'db_table': 'open_chat_rooms',
            },
        ),
        migrations.CreateModel(
            name='OpenChat',
            fields=[
                ('id', models.BigIntegerField(default=common.snowflake.generate_id, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_time', models.DateTimeField(blank=True, null=True)),
                ('message', models.TextField()),
                ('message_type', models.IntegerField(choices=[(1, 'Text'), (2, 'Image'), (3, 'Video'), (4, 'File')], default=1)),
                ('sender', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='users.user')),
                ('open_chat_room', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='open_chats.openchatroom')),
            ],
            options={
                'db_table': 'open_chats',
            },
        ),
        migrations.CreateModel(
            name='OpenChatRoomMembershipRequest',
            fields=[
                ('id', models.BigIntegerField(default=common.snowflake.generate_id, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_time', models.DateTimeField(blank=True, null=True)),
                ('message', models.CharField(max_length=255)),
                ('status', models.IntegerField(choices=[(1, 'Pending'), (2, 'Accepted'), (3, 'Rejected')], default=1)),
                ('open_chat_room', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='open_chats.openchatroom')),
                ('requester', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='users.user')),
            ],
            options={
                'db_table': 'open_chat_room_membership_requests',
            },
        ),
        migrations.CreateModel(
            name='OpenChatRoomUser',
            fields=[
                ('id', models.BigIntegerField(default=common.snowflake.generate_id, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_time', models.DateTimeField(blank=True, null=True)),
                ('last_exit_time', models.DateTimeField(auto_now_add=True)),
                ('open_chat_room', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='open_chats.openchatroom')),
                ('user', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='users.user')),
            ],
            options={
                'db_table': 'open_chat_room_users',
            },
        ),
        migrations.AddIndex(
            model_name='openchatroom',
            index=models.Index(fields=['category'], name='open_chat_r_categor_887c8c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='openchatroom',
            unique_together={('manager', 'title')},
        ),
        migrations.AlterUniqueTogether(
            name='openchatroommembershiprequest',
            unique_together={('requester', 'open_chat_room')},
        ),
        migrations.AlterUniqueTogether(
            name='openchatroomuser',
            unique_together={('user', 'open_chat_room')},
        ),
    ]
