# Generated by Django 5.2.3 on 2025-06-27 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('open_chats', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='openchat',
            old_name='deleted_time',
            new_name='deleted_at',
        ),
        migrations.RenameField(
            model_name='openchatroom',
            old_name='deleted_time',
            new_name='deleted_at',
        ),
        migrations.RenameField(
            model_name='openchatroommembershiprequest',
            old_name='deleted_time',
            new_name='deleted_at',
        ),
        migrations.RenameField(
            model_name='openchatroomuser',
            old_name='deleted_time',
            new_name='deleted_at',
        ),
    ]
